// <auto-generated />
using System;
using Libreria_Lecturas.Implementaciones;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Libreria_Lecturas.Migrations
{
    [DbContext(typeof(Conexion))]
    [Migration("20260527140933_AgregarCamposHistorialLecturas")]
    partial class AgregarCamposHistorialLecturas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Libreria_Lecturas.Entidades.Autores", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nacionalidad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Autores");
                });

            modelBuilder.Entity("Libreria_Lecturas.Entidades.CalendarioLecturas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("PaginasLeidas")
                        .HasColumnType("int");

                    b.Property<decimal>("TiempoMinutos")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("CalendarioLecturas");
                });

            modelBuilder.Entity("Libreria_Lecturas.Entidades.ConfiguracionUsuarios", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("NotificacionesActivas")
                        .HasColumnType("bit");

                    b.Property<bool?>("TemaOscuro")
                        .HasColumnType("bit");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("ConfiguracionUsuarios");
                });

            modelBuilder.Entity("Libreria_Lecturas.Entidades.Editoriales", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Activa")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("AnoFundacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pais")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Editoriales");
                });

            modelBuilder.Entity("Libreria_Lecturas.Entidades.Estadisticas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("LibrosLeidos")
                        .HasColumnType("int");

                    b.Property<int>("PaginasTotales")
                        .HasColumnType("int");

                    b.Property<decimal>("PromedioPaginas")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Estadisticas");
                });

            modelBuilder.Entity("Libreria_Lecturas.Entidades.EstadoLecturas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EstadoLecturas");
                });

            modelBuilder.Entity("Libreria_Lecturas.Entidades.Favoritos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaMarcado")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LibroId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LibroId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Favoritos");
                });

            modelBuilder.Entity("Libreria_Lecturas.Entidades.Generos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Generos");
                });

            modelBuilder.Entity("Libreria_Lecturas.Entidades.HistorialLecturas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LibroId")
                        .HasColumnType("int");

                    b.Property<int?>("PaginasLeidas")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LibroId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("HistorialLecturas");
                });

            modelBuilder.Entity("Libreria_Lecturas.Entidades.Lecturas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LibroId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LibroId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Lecturas");
                });

            modelBuilder.Entity("Libreria_Lecturas.Entidades.Libros", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AnoPublicacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Autor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("AutorId")
                        .HasColumnType("int");

                    b.Property<int?>("GeneroId")
                        .HasColumnType("int");

                    b.Property<int>("PaginasTotales")
                        .HasColumnType("int");

                    b.Property<string>("Sinopsis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AutorId");

                    b.HasIndex("GeneroId");

                    b.ToTable("Libros");
                });

            modelBuilder.Entity("Libreria_Lecturas.Entidades.Logros", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Puntos")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Logros");
                });

            modelBuilder.Entity("Libreria_Lecturas.Entidades.MetaLecturas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Ano")
                        .HasColumnType("int");

                    b.Property<decimal>("CantidadObjetivo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("LibrosCompletos")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("MetaLecturas");
                });

            modelBuilder.Entity("Libreria_Lecturas.Entidades.Notas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Contenido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("Pagina")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Notas");
                });

            modelBuilder.Entity("Libreria_Lecturas.Entidades.Notificaciones", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("FechaEnvio")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Leida")
                        .HasColumnType("bit");

                    b.Property<string>("Mensaje")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Notificaciones");
                });

            modelBuilder.Entity("Libreria_Lecturas.Entidades.ProgresoLecturas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LecturaId")
                        .HasColumnType("int");

                    b.Property<int>("PaginasLeidas")
                        .HasColumnType("int");

                    b.Property<decimal>("Porcentaje")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("LecturaId");

                    b.ToTable("ProgresoLecturas");
                });

            modelBuilder.Entity("Libreria_Lecturas.Entidades.Recomendaciones", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("Motivo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Recomendaciones");
                });

            modelBuilder.Entity("Libreria_Lecturas.Entidades.Resenas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Calificacion")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Comentario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LibroId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LibroId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Resenas");
                });

            modelBuilder.Entity("Libreria_Lecturas.Entidades.SeccionLecturas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("MinutosLeidos")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PaginasLeidas")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SeccionLecturas");
                });

            modelBuilder.Entity("Libreria_Lecturas.Entidades.Usuarios", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<int>("LibrosLeidos")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PaginasLeidas")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Libreria_Lecturas.Entidades.CalendarioLecturas", b =>
                {
                    b.HasOne("Libreria_Lecturas.Entidades.Usuarios", "_UsuarioId")
                        .WithMany()
                        .HasForeignKey("UsuarioId");

                    b.Navigation("_UsuarioId");
                });

            modelBuilder.Entity("Libreria_Lecturas.Entidades.ConfiguracionUsuarios", b =>
                {
                    b.HasOne("Libreria_Lecturas.Entidades.Usuarios", "_UsuarioId")
                        .WithMany("_ConfiguracionUsuarios")
                        .HasForeignKey("UsuarioId");

                    b.Navigation("_UsuarioId");
                });

            modelBuilder.Entity("Libreria_Lecturas.Entidades.Favoritos", b =>
                {
                    b.HasOne("Libreria_Lecturas.Entidades.Libros", "_LibroId")
                        .WithMany("_Favoritos")
                        .HasForeignKey("LibroId");

                    b.HasOne("Libreria_Lecturas.Entidades.Usuarios", "_UsuarioId")
                        .WithMany("_Favoritos")
                        .HasForeignKey("UsuarioId");

                    b.Navigation("_LibroId");

                    b.Navigation("_UsuarioId");
                });

            modelBuilder.Entity("Libreria_Lecturas.Entidades.HistorialLecturas", b =>
                {
                    b.HasOne("Libreria_Lecturas.Entidades.Libros", "_LibroId")
                        .WithMany()
                        .HasForeignKey("LibroId");

                    b.HasOne("Libreria_Lecturas.Entidades.Usuarios", "_UsuarioId")
                        .WithMany()
                        .HasForeignKey("UsuarioId");

                    b.Navigation("_LibroId");

                    b.Navigation("_UsuarioId");
                });

            modelBuilder.Entity("Libreria_Lecturas.Entidades.Lecturas", b =>
                {
                    b.HasOne("Libreria_Lecturas.Entidades.Libros", "_LibroId")
                        .WithMany("_Lecturas")
                        .HasForeignKey("LibroId");

                    b.HasOne("Libreria_Lecturas.Entidades.Usuarios", "_UsuarioId")
                        .WithMany("_Lecturas")
                        .HasForeignKey("UsuarioId");

                    b.Navigation("_LibroId");

                    b.Navigation("_UsuarioId");
                });

            modelBuilder.Entity("Libreria_Lecturas.Entidades.Libros", b =>
                {
                    b.HasOne("Libreria_Lecturas.Entidades.Autores", "_AutorId")
                        .WithMany("_Libros")
                        .HasForeignKey("AutorId");

                    b.HasOne("Libreria_Lecturas.Entidades.Generos", "_GeneroId")
                        .WithMany("_Libros")
                        .HasForeignKey("GeneroId");

                    b.Navigation("_AutorId");

                    b.Navigation("_GeneroId");
                });

            modelBuilder.Entity("Libreria_Lecturas.Entidades.MetaLecturas", b =>
                {
                    b.HasOne("Libreria_Lecturas.Entidades.Usuarios", "_UsuarioId")
                        .WithMany("_MetaLecturas")
                        .HasForeignKey("UsuarioId");

                    b.Navigation("_UsuarioId");
                });

            modelBuilder.Entity("Libreria_Lecturas.Entidades.Notificaciones", b =>
                {
                    b.HasOne("Libreria_Lecturas.Entidades.Usuarios", "_UsuarioId")
                        .WithMany("_Notificaciones")
                        .HasForeignKey("UsuarioId");

                    b.Navigation("_UsuarioId");
                });

            modelBuilder.Entity("Libreria_Lecturas.Entidades.ProgresoLecturas", b =>
                {
                    b.HasOne("Libreria_Lecturas.Entidades.Lecturas", "_LecturaId")
                        .WithMany("_ProgresoLecturas")
                        .HasForeignKey("LecturaId");

                    b.Navigation("_LecturaId");
                });

            modelBuilder.Entity("Libreria_Lecturas.Entidades.Resenas", b =>
                {
                    b.HasOne("Libreria_Lecturas.Entidades.Libros", "_LibroId")
                        .WithMany("_Resenas")
                        .HasForeignKey("LibroId");

                    b.HasOne("Libreria_Lecturas.Entidades.Usuarios", "_UsuarioId")
                        .WithMany("_Resenas")
                        .HasForeignKey("UsuarioId");

                    b.Navigation("_LibroId");

                    b.Navigation("_UsuarioId");
                });

            modelBuilder.Entity("Libreria_Lecturas.Entidades.Autores", b =>
                {
                    b.Navigation("_Libros");
                });

            modelBuilder.Entity("Libreria_Lecturas.Entidades.Generos", b =>
                {
                    b.Navigation("_Libros");
                });

            modelBuilder.Entity("Libreria_Lecturas.Entidades.Lecturas", b =>
                {
                    b.Navigation("_ProgresoLecturas");
                });

            modelBuilder.Entity("Libreria_Lecturas.Entidades.Libros", b =>
                {
                    b.Navigation("_Favoritos");

                    b.Navigation("_Lecturas");

                    b.Navigation("_Resenas");
                });

            modelBuilder.Entity("Libreria_Lecturas.Entidades.Usuarios", b =>
                {
                    b.Navigation("_ConfiguracionUsuarios");

                    b.Navigation("_Favoritos");

                    b.Navigation("_Lecturas");

                    b.Navigation("_MetaLecturas");

                    b.Navigation("_Notificaciones");

                    b.Navigation("_Resenas");
                });
#pragma warning restore 612, 618
        }
    }
}
